site_name: 个人博客
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: simple/kaios
        name: 特别配色
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 浅色模式
    - media:
      scheme: kokomi
      toggle:
        icon: material/brightness-7
        name: 深色模式

  name: material
  features:
    - search.highlight
    - search.share

plugins:
  - search:
      lang: en
extra_css:
  - stylesheets/extra.css
