site_name: 个人博客
site_url: http://yan-xiaoo.github.io
site_author: 李彦筱

nav:
  - 随笔:
    - 有道年卡奖学金: diary/有道词典奖学金.md

theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: simple/kaios
        name: 特别配色
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 浅色模式
    - media: 
      scheme: kokomi
      toggle:
        icon: material/brightness-7
        name: 深色模式

  name: material
  features:
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
  language: zh
  font:
    text: Noto Sans SC

plugins:
  - search:
      lang: en
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html