authors:
  yan_xiaoo:
    name: YanXiao
    description: A student in XJTU 
    avatar: https://avatars.githubusercontent.com/u/81431446
    # slug: url           # Author profile slug
    url: https://github.com/yan-xiaoo 